sudo: required
services:
  - docker
language: generic
before_install:
  - docker build -t ph1n34s/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true ph1n34s/react-test npm test

after_success:
  - docker build -t ph1n34s/multi-client ./client
  - docker build -t ph1n34s/multi-nginx ./nginx
  - docker build -t ph1n34s/multi-server ./server
  - docker build -t ph1n34s/multi-worker ./worker
  # Take those images and push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ph1n34s/multi-client
  - docker push ph1n34s/multi-nginx
  - docker push ph1n34s/multi-server
  - docker push ph1n34s/multi-worker
